# Carga de paquetes --------------------------------------------------------------------------------
message( paste( rep( '-', 100 ), collapse = '' ) )
message( '\tCargando paquetes' )

suppressPackageStartupMessages( library( actuar ) )
suppressPackageStartupMessages( library( colorRamps ) )
suppressPackageStartupMessages( library( data.table ) )
suppressPackageStartupMessages( library( digest ) )
suppressPackageStartupMessages( library( extrafont ) )
suppressPackageStartupMessages( library( lubridate ) )
suppressPackageStartupMessages( library( Hmisc ) )
suppressPackageStartupMessages( library( knitr ) )
suppressPackageStartupMessages( library( ks ) )
#suppressPackageStartupMessages( library( KRIG ) )
suppressPackageStartupMessages( library( MASS ) )
suppressPackageStartupMessages( library( pracma ) )
suppressPackageStartupMessages( library( reshape2 ) )
suppressPackageStartupMessages( library( stringr ) )
suppressPackageStartupMessages( library( xtable ) )
suppressPackageStartupMessages( library( readxl ) )
suppressPackageStartupMessages( library( ggplot2 ) )
suppressPackageStartupMessages( library( gridExtra ) )
suppressPackageStartupMessages( library( RColorBrewer ) )
suppressPackageStartupMessages( library( RcppRoll ) )
suppressPackageStartupMessages( library( quadprog ) )
suppressPackageStartupMessages( library( rgl ) )
suppressPackageStartupMessages( library( splines ) )
suppressPackageStartupMessages( library( marima ) )
suppressPackageStartupMessages( library( scales ) )
suppressPackageStartupMessages( library( ggthemes ) )
suppressPackageStartupMessages( library( ggrepel ) )
suppressPackageStartupMessages( library( XLConnect ) )
suppressPackageStartupMessages( library( readr ) )
suppressPackageStartupMessages( library( janitor ) )
suppressPackageStartupMessages( library( eeptools ) )
suppressPackageStartupMessages( library( ggmap ) )
suppressPackageStartupMessages( library( grid ) )
suppressPackageStartupMessages( library( latex2exp ) )
suppressPackageStartupMessages( library( ggpubr ) )
suppressPackageStartupMessages( library( stargazer ) )
suppressPackageStartupMessages( library( dplyr, warn.conflicts = FALSE ) )
suppressPackageStartupMessages( library( dtplyr ) )
suppressPackageStartupMessages( library( tidyr ) )
#suppressPackageStartupMessages( library( openxlsx ) )

suppressMessages( loadfonts() )

message( paste( rep( '-', 100 ), collapse = '' ) )
